### ISSUE TITLE
Error with waveform plot

### ISSUE THREAD

**Issue by ErikHogenbirk** [XENON1T/hax#10]
I'm not really sure if this is a pax or hax issue, but I'm unable to plot from my notebook. Will try plotting directly from pax.

Input: https://gist.github.com/ErikHogenbirk/25d4f8808ce5fb70b51fcadca99f4a2a
Output: https://gist.github.com/ErikHogenbirk/33b0e735ac0677a6abdeb39912c1ca3d

It seems the data is found and read; there is a checkpulses warning at the beginning. Then it throws some ROOT error and everything goes wrong.

pax 4.8.0
hax 0.1

**Comment by tunnell** [comment]
I think @alecstein also saw this. It's a ROOT issue, maybe due to how ROOT changes how other modules get imported?  If you import ROOT first, does that help?

**Comment by ErikHogenbirk** [comment]
i.e. `` import root``` before ```import hax```? No luck, the same

**Comment by JelleAalbers** [comment]
Maybe try switching to root 6 in your environment?

**Comment by tunnell** [comment]
Import matplotlib then ROOT then hax?  I'd just do the combinatorical combinations with matplotlib, ROOT, hax, and whatever else you see throwing errors.

**Comment by ErikHogenbirk** [comment]
Thanks for your suggestions, will try them asap. Right now don't have time for it I'm afraid, may be Monday

**Comment by tunnell** [comment]
still an issue?

**Comment by ErikHogenbirk** [comment]
I was actually just now able to plot in notebook for the first time. I still don't know where the issue came from but it's fixed now. (I updated pax and hax in the meantime, now at 4.9.1 and 0.2, respectively. Maybe it's fixed in recent version?)
