### ISSUE TITLE
Hax.runs.tags_selection no longer supports exclude-only

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/hax#120]
The tag version printing logic introduced in hax.runs.tags_selection (https://github.com/XENON1T/hax/blob/master/hax/runs.py#L342) assumes there is always an include tag. If you try to do e.g.

    hax.runs.tags_selection(exclude=['bad', 'worse', 'terrible'])

you will now get an error ('NoneType' object is not iterable).

**Comment by JelleAalbers** [comment]
As a workaround, you can still use the lower-level function:

    dsets = hax.runs.datasets
    dsets = dsets[True ^ hax.runs._tags_match(dsets, ['bad', 'worse', 'terrible'], pattern_type='fnmatch', ignore_underscore=True)]

**Comment by feigaodm** [comment]
@coderdj Any progress on this issue? It looks like more analizers are hitting this issue.

**Comment by coderdj** [comment]
I'll look. My preferred solution is to remove functionality already covered by another package (in this case pymongo, which is what I use to select runlists).

**Comment by coderdj** [comment]
(didn't mean to close, clicked wrong button)
