### ISSUE TITLE
MC minitree generation (with Corrections minitree)

### ISSUE THREAD

**Issue by l-althueser** [XENON1T/hax#135]
See my comment here: https://github.com/XENON1T/hax/commit/85ba0b2a4ea4e8b7f52b2c7f243d13ad1c8c3dae#commitcomment-23700727

The issue can be reproduced by running the MC full chain or Patricks small code example:
```
export PATH="/project/lgrandi/anaconda3/bin:$PATH"
source activate pax_v6.8.0
haxer --main_data_paths . --input /project/lgrandi/pdeperio/170817-lutz/Xenon1T_TPC_Kr83m_00000_g4mc_NEST_Patch_pax --pax_version_policy loose --treemakers Corrections Basics --force_reload
```

Full error traceback here: https://gist.github.com/l-althueser/e10a2e96e688e16d7e4b0b06a46c50ea#file-run_sim-sh-out-L2765

**Comment by l-althueser** [comment]
Next issue after this fix is this:

```
Traceback
---------
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/dask/async.py&quot;, line 263, in execute_task
    result = _execute_task(task, data)
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/dask/async.py&quot;, line 245, in _execute_task
    return func(*args2)
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/dask/compatibility.py&quot;, line 47, in apply
    return func(*args, **kwargs)
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/hax-1.6.2-py3.4.egg/hax/minitrees.py&quot;, line 378, in load_single_dataset
    run_id, treemaker, force_reload=force_reload, event_list=event_list)
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/hax-1.6.2-py3.4.egg/hax/minitrees.py&quot;, line 325, in load_single_minitree
    skimmed_data = treemaker().get_data(run_id, event_list=event_list)
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/hax-1.6.2-py3.4.egg/hax/minitrees.py&quot;, line 92, in get_data
    desc=&apos;Making %s minitree&apos; % self.__class__.__name__)
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/hax-1.6.2-py3.4.egg/hax/paxroot.py&quot;, line 165, in loop_over_datasets
    for _ in function_results_datasets(*args, **kwargs):
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/hax-1.6.2-py3.4.egg/hax/paxroot.py&quot;, line 157, in function_results_datasets
    raise e
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/hax-1.6.2-py3.4.egg/hax/paxroot.py&quot;, line 151, in function_results_datasets
    yield event_function(event, **kwargs)
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/hax-1.6.2-py3.4.egg/hax/minitrees.py&quot;, line 75, in process_event
    result = self.extract_data(event)
  File &quot;/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_head/lib/python3.4/site-packages/hax-1.6.2-py3.4.egg/hax/treemakers/corrections.py&quot;, line 152, in extract_data
    ts = ((self.run_start - np.datetime64(&apos;1970-01-01T00:00:00Z&apos;)) /
```

**Comment by feigaodm** [comment]
Are you using Corrections minitrees? I think we won't see this problem if you delete Corrections minitrees. Is it really needed for your purpose?

**Comment by coderdj** [comment]
This isn't a bug, it's just behavior we didn't consider yet. Of course if you want to apply a correction it will use the date and run number to choose the proper one. Particularly the electron lifetime correction, which changes quite quickly as a function of time, is parameterized as a function of date.

What behavior are you looking for? What should the corrections do and how should they be chosen? If you need corrections in MC one possible solution could be to generate all the MC according to the parameters of some random run in the middle of the exposure and use that run for processing.

**Comment by l-althueser** [comment]
We didn't consider it yet for the new corrections minitree, but we have used the `cs1` and `cs2` for the MC before (and that is why I am asking for this ;) ). I am not the expert for full chain MCs but I think that the only showstopper is the electron lifetime correction which is now applied different. I don't know if we need this for the MC (depends on what FAX is doing ..).
How was this correction applied in HAX v1.5.0?

**Comment by l-althueser** [comment]
At some later point in the MC chain (if I exclude the generation of the Corrections minitree) the Correction minitree is again requested by LAX (see [here](https://github.com/XENON1T/processing/blob/master/montecarlo/run_sim.sh#L411)): 
```
DEBUG:hax.minitrees] Minitree Xenon1T_TPC_Kr83m_00187_g4mc_NEST_Patch_pax_Corrections.root not found
DEBUG:hax.minitrees] Not found in non-preferred formats either. Minitree will be created.
```
We can now decide if this is a MC issue (and change the processing + LAX) or a not implemented feature of HAX (which is needed to run the full chain).

**Comment by coderdj** [comment]
The easiest would be to just have the electron lifetime code in hax made more robust to handle this case (try/except, put value of '1' if fails). But I think we have to know what the full chain MC is expecting. If the attenuation with depth due to electron lifetime is simulated then it should also be corrected with a proper value.

**Comment by l-althueser** [comment]
We use a specific electron lifetime ([in the MC](https://github.com/XENON1T/processing/blob/master/montecarlo/run_sim.sh#L329)) to simulate in [FAX the S2 electrons](https://github.com/XENON1T/pax/blob/master/pax/simulation.py#L541). The lifetime which is used there is extracted from data before ([set here](https://github.com/XENON1T/processing/blob/master/montecarlo/run_sim.sh#L77)). I think that this means that we can wrap the electron lifetime correction in a try/except block and use 1.

**Comment by coderdj** [comment]
Doesn't this just mean you need to use 550 mus (not '1')?

**Comment by l-althueser** [comment]
This would make more sense! In the end we need a test if a MC is used and then get the `electron_lifetime_liquid=${ELECTRON_LIFETIME} * us` from the config. This would mean that we have to warn MC producer to only use the minitrees generated from the full chain (or to set the config properly while generating).

**Comment by pdeperio** [comment]
@l-althueser What you correctly describe is how the e-lifetime is included in the simulation.  However, the issue is in the reconstruction (aka correction).  Previously, the ```electron_lifetime_liquid``` value to correct with was coming from the same pax config that is used to simulate (fax), as you showed [here](https://github.com/XENON1T/processing/blob/master/montecarlo/run_sim.sh#L329).  This one config parameter fed both the [fax simulation](https://github.com/XENON1T/pax/blob/master/pax/simulation.py#L541) and [pax reconstruction/correction](
https://github.com/XENON1T/pax/blob/master/pax/plugins/interaction_processing/BuildInteractions.py#L85).

Now that this correction has been moved out of pax into hax, we would need a corresponding config option to set the lifetime [here](https://github.com/XENON1T/hax/blob/85ba0b2a4ea4e8b7f52b2c7f243d13ad1c8c3dae/hax/treemakers/corrections.py#L59).  @coderdj is this something you could implement (like in pax)?

**Comment by feigaodm** [comment]
Isn't it dangerous to modify [correction treemaker](https://github.com/XENON1T/hax/blob/85ba0b2a4ea4e8b7f52b2c7f243d13ad1c8c3dae/hax/treemakers/corrections.py#L59) directly? Then if something weired happen for real data, we will insert a bad e-life for correction. Can we add some flag to tell if it's from simulation and use the default value in pax if it is?

**Comment by pdeperio** [comment]
true.  can we have fax set some negative time and/or run number?

**Comment by pdeperio** [comment]
Other run dependent parameters in [fax](https://github.com/XENON1T/pax/blob/master/pax/simulation.py#L89) and [hax](https://github.com/XENON1T/hax/blob/master/hax/treemakers/corrections.py#L70), such as S1, S2, and FDC maps, will also need to be considered similarly.

For now, I've reverted the CVMFS environments (```pax_v6.6.5```, ```pax_v6.6.6```, ```pax_v6.8.0```) to the last working hax commit (https://github.com/XENON1T/hax/commit/aadb15b4d19316f778baebea7fcc9a00470cd432).  This should allow MC production to continue, while real data still uses ```v1.6.2``` on Midway with the ```/project/lgrandi/anaconda3``` installation.
