### ISSUE TITLE
Strange muon_veto_trigger nonsense

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/hax#159]
Andrea Molinario @molinario Oct 27 09:37 wrote:
 
> I am working with Proximity minitrees which I find in ```/project2/lgrandi/xenon1t/minitrees/pax_v6.8.0```. I found weird values of the nearest ```muon_veto_trigger``` in few runs. These values are completely out of sense (order 368 million seconds!). I checked and, in those runs, the list of MV triggers times in the acquisition monitor was present and with reasonable values.
> These runs are 12355, 12359 and 12360
> If I rebuild the Proximity minitrees myself with a Jupyter notebook, I get reasonable values for the nearest_muon_veto trigger.
> Any suggestion on what is going on here?

Daniel Coderre @coderdj 15:14 wrote:
> Is there a log of the error? If it failed before and worked now my only guess is a corrupted acquisition monitor file

We confirmed that regrowing 12355 (```/project2/lgrandi/xenon1t/minitrees/pax_v6.8.0/170823_1847_Proximity.root```) fixed it. However, nothing strange found in the logs:
```
/project/lgrandi/xenon1t/cax/12355_v6.8.0/12355_v6.8.0_35603636.log
/project/lgrandi/xenon1t/cax/12359_v6.8.0/12359_v6.8.0_35625285.log
/project/lgrandi/xenon1t/cax/12360_v6.8.0/12360_v6.8.0_35603630.log
```

I've moved the remaining 2 runs to:
```
/project/lgrandi/xenon1t/minitrees/pax_v6.8.0/hax_issue_159
```
for future investigation and regrown them in the official directory.

**Comment by molinario** [comment]
I checked the runs 12359 and 12360. The regrowing fixed the problem for them as well.

**Comment by pdeperio** [comment]
On Oct 31, 2017, at 10:51 AM, Andrea Molinario @molinario  wrote:

> I send you a list of runs for which we can try to regrow the Proximity minitrees. You will see they are a good number. You can understand the reason by looking at the attached picture, which shows how the time difference between MV and high energy TPC events changes in time during SR1. These high energy TPC events are due to muons crossing the detector, so we would expect a tight time coincidence with MV. This is almost always the case, except for a few cases here and there and a specific period going from August 23rd to September 4th. The 3 runs you have already regrown belong to this period. Maybe it's even better to regrow Proximity for all runs in this period, and not only for those mentioned in my list.
> 
> I don't know why this is happening. I re-produced the Proximity minitree myself for few of these runs and I found that the MV-TPC time differences for high energy events change, getting to the expected value typical of physical coincidence among the two detectors.

![sr1_171024_2](https://user-images.githubusercontent.com/8642192/32231017-e09f7024-be2a-11e7-8988-821cb1f9cd72.png)
[list_run.txt](https://github.com/XENON1T/hax/files/1431139/list_run.txt)

**Comment by pdeperio** [comment]
@molinario ok i've regrown your list of runs. please check and let me know if i missed any.
