### ISSUE TITLE
Peak, Hit, etc. data access

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/hax#16]
It would be nice to include a bit of code to extract all peaks, hits, etc. from a file, with an extra column which tells you which event they came from. This doesn't have to be very fast, as it is not a very common analysis task, though ideally it should not fry your RAM (so maybe allow for some chunking). 

The peaks in particular are useful to plot in exploratory analyses (see e.g. the graphs in [Erik's GXe note](https://xecluster.lngs.infn.it/dokuwiki/lib/exe/fetch.php?media=xenon:xenon1t:r81_gas_s2.html), even though those were only produced for the largest peaks since that's what hax currently allows you to do conveniently). The hits and pulses are useful for gain calibrations and hitfinder efficiency studies. 

You can write your own code to do this of course, e.g. with  `hax.paxroot.looproot; I and others have some code like that -- a nice version of this would be a good addition to hax.

**Comment by ErikHogenbirk** [comment]
I'm working on this, so if anyone else is interested (i.e. working on this or wanting to get this data) please let me know. Hope to add sth to hax for this soon.

**Comment by JelleAalbers** [comment]
This has been added in #20, we may still chance the interface a bit or integrate it more with hax.minitrees, but the functionality is all there. Thanks again Erik!
