### ISSUE TITLE
Need proper corrections in DoubleScatter treemaker

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/hax#160]
Corrections for single scatter analysis are now being done in hax [here for S2](https://github.com/XENON1T/hax/blob/v1.9.0/hax/treemakers/corrections.py#L193) and [here for S1](https://github.com/XENON1T/hax/blob/v1.9.0/hax/treemakers/corrections.py#L268), instead of in pax. These should be implemented in the [```DoubleScatter``` treemaker](https://github.com/XENON1T/hax/blob/v1.9.0/hax/treemakers/DoubleScatter.py#L254) similarly.

**Comment by feigaodm** [comment]
I would rename the DoubleScatter here as DoubleS1Scatter to clarify. The correction logic will be very different. For double S2 scatter (like neutron background or high energy comptons), the correction on S1 will probably not be necessary.

**Comment by feigaodm** [comment]
should be fixed by PR (#170)
