### ISSUE TITLE
Get more XENON1T run info

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/hax#17]
Currently only some very basic info is queried from the db -- name, number and source. We should get several more fields for the analyst to use, such as timestamp, tags, duration, ... . There should also be a utility function to get all the info from a specific run (the complete json).

**Comment by tunnell** [comment]
And electron lifetime.

**Comment by JelleAalbers** [comment]
The fields described above are now in `hax.runs.datasets` (except for electron lifetime, since that isn't in the runs db yet), and you get complete run docs with `hax.runs.get_run_info`. Of course these only work if you set `experiment=XENON1T` in `hax.init` -- I expect this should become the default soon.
