### ISSUE TITLE
can't cope with trigger information

### ISSUE THREAD

**Issue by ErikHogenbirk** [XENON1T/hax#19]
When calling ```hax.raw_data.inspect_events(198,0)``` I get an error about the name of the trigger info:

    ValueError: Invalid file name: /xetemp/xenon1t/160425_1103/trigger_monitor_data.zip. 
    Should be tpcname-something-firstevent-lastevent-nevents.zip

I guess this is due to the recent addition of trigger zipped bsons?
pax 4.9.1, hax 0.2, running on xecluster06, trying to read from /xetemp/xenon1t/

**Comment by JelleAalbers** [comment]
Yes, this was a bug, should be fixed in https://github.com/XENON1T/pax/pull/348

**Comment by ErikHogenbirk** [comment]
Seems this was actually a pax issue and not hax ;) sometimes hard to tell them apart. Anyhow, the issue is fixed, thank you!
