### ISSUE TITLE
Making minitree for Monte Carlo data

### ISSUE THREAD

**Issue by ctherreau** [XENON1T/hax#225]
When trying to make minitrees from processed MonteCarlo data using :

`
hax.init(experiment='XENON1T', minitree_paths = [path, path_mc+ '/minitrees/',],
              main_data_paths = [path_mc +'/processed/'],
              pax_version_policy= 'loose',
              make_minitrees = True, 
             use_runs_db=False,
             blinding_cut = 'event_number > -1'
         )
`
`df = hax.minitrees.load(run_names, treemakers=[ExtendedCorrectedDoubleS1Scatter],force_reload=True)
`

An assertion error appears (all detail here: 
https://gist.github.com/ctherreau/8ad46f836ff14ddd5e8e354b6d45a6e5) 

From the gitter chat (thanks Jelle, Sander, Lutz), the solution is to add : 
`hax.runs.get_run_number = lambda x: 0`

It would be nice to have a more permanent solution.

**Comment by l-althueser** [comment]
We figured out that our older MC productions can not be loaded with the recent HAX version due to changes in the MC file handling/detection. It is easier to redo the MCs than changing HAX or hacking a function in it. Thanks to all!
