### ISSUE TITLE
when loading data: ValueError: Metadata mismatch found in `from_delayed`

### ISSUE THREAD

**Issue by NataschaRupp** [XENON1T/hax#232]
Hi,
I would like to load data after SR1 (in the example Feb 1, 2018 - Feb 3, 2018). It seems like there is a mismatched between expected data type and found data type. I attached a notebook where one can reproduce the error and the error message itself. I run on midway2-login2.
 
[hax_issue.ipynb.zip](https://github.com/XENON1T/hax/files/2089794/hax_issue.ipynb.zip)

[error_message.pdf](https://github.com/XENON1T/hax/files/2089790/error_message.pdf)

Thanks, Natascha

**Comment by LeafSwordy** [comment]
Hi,
I got a similar error, but I am using pax v6.8.0.

[hax_issue_6.8.0.ipynb.zip](https://github.com/XENON1T/hax/files/2122990/hax_issue_6.8.0.ipynb.zip)
[metadata_error.txt](https://github.com/XENON1T/hax/files/2122991/metadata_error.txt)

**Comment by pdeperio** [comment]
Can you tell which run is failing? (I guess run ```16516```, which has a very small number of events. @JelleAalbers do you think https://github.com/XENON1T/hax/issues/47 is related?)

**Comment by AlexElykov** [comment]
Hi, 

@pdeperio 

Encountered the same issue as above while loading NG data, caused by Proximity minitree. Can try to give more details if needed.

**Comment by MAVJ** [comment]
Hi @pdeperio, 
Just that somebody knows, I went through the whole background data in SR1 and found similar errors for the following runs:

6932, 6945, 7148, 7178, 7181, 9383, 9398, 10579, 11019, 12736, 13423, 13554

**Comment by JelleAalbers** [comment]
This should be solved by #236. If you still see this in recent hax versions, let me know, and I can have a look.
