### ISSUE TITLE
Add init option: folder to save minitrees in (feature request)

### ISSUE THREAD

**Issue by sanderbreur** [XENON1T/hax#25]
Right now the minitrees get created in the folder where hax is called. To keep a nice and clean work space it would be better if one could specify where hax creates the minitrees. The standard option would still be: in this folder, but the user could specify one folder that holds all the minitrees that one uses.

Hax would also need to find the minitrees in the user specified folder.

**Comment by JelleAalbers** [comment]
You can now set `minitree_paths = ['blaa', 'other_dir', 'yet_another_dir']`; hax will always create minitrees in the first folder (`blaa` in this example), and it checks for minitrees in all the dirs (starting with the first, then processing down the list). If the creation directory does not exists, hax will create it; it's your responsibility you have the permissions to do this. By default the creation dir is still '.'.

Previously there was an option `mini_tree_paths`, but it did not affect where minitrees were created.

**Comment by sanderbreur** [comment]
Perfect, thanks, good job!
