### ISSUE TITLE
Add init option: mongodb = False

### ISSUE THREAD

**Issue by sanderbreur** [XENON1T/hax#27]
For people who want to run hax locally on their laptop without using the rundb info it would be nice to have an init option for hax to work without the db and thus without setting a mongodb password. (this works with experiment = 'XENON100', but not anymore with experiment = 'XENON1T') 

Even though hax is created with analysis facilities in mind, making a small option that lets you work locally is still a very nice feature that me and others use.

**Comment by tunnell** [comment]
At the loss of run DB information.

**Comment by sanderbreur** [comment]
Yes, so on all analysis facilities you would always want to run with
mongodb. But for quick tests on my local machine I can choose to not use it.
