### ISSUE TITLE
Fields missing from LargestPeakProperties minitree

### ISSUE THREAD

**Issue by pelssers** [XENON1T/hax#42]
When making minitrees of pax v6.1.0 data on midway with LargestPeakProperties the *_x and *_y fields are missing.

To reproduce:
```python
import hax
hax.init(pax_version_policy='6.1.0')
data = hax.minitrees.load(2047, treemakers=['LargestPeakProperties'], force_reload=True, num_workers=1)
data.keys()
```

**Comment by JelleAalbers** [comment]
I think this got fixed in #104 / #102 . And I think it might be hard to retrieve run 2047 anymore :-)
