### ISSUE TITLE
Dump minitree to file

### ISSUE THREAD

**Issue by ErikHogenbirk** [XENON1T/hax#45]
I've used the cache_file option in minitrees.load, and I was thinking that this is maybe something you'd also want for a normal minitree. For instance, suppose you apply a bunch of cuts and you keep only a small number of events (like the NR single scatter band), and you want to share this with a collegue (or some other script if you don't have any friends). It'd be nice to be able to load and store minitrees in a standard haxy way.
I think it would be quite easy to make, if people agree that this could be useful I'll make the code and make a pull request. If not then I'll shut up about it and just use pickle for my own code :)

**Comment by JelleAalbers** [comment]
Pandas may have something that helps you: `nicedata.to_hdf('myfile.hdf5', 'data')`, load back with `nicedata = pd.read_hdf('myfile.hdf5', 'data')` (I think, haven't checked exact syntax)

**Comment by JelleAalbers** [comment]
This was addressed by `hax.minitrees.save_cache_file` and `hax.minitrees.load_cache_file`. These save a minitree-derived dataframe, preserving the cut history between saves and loads.
