### ISSUE TITLE
Missing Branches in Output

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/hax#47]
The ```lone_hit_*``` branches are missing in some ```LargestPeakProperties``` minitrees, causing problems in the MC workflow. Can reproduce with files on Midway in:
```
/project/lgrandi/pdeperio/161206-hax_debug
```
by running:
```
source activate pax_v6.1.1
HAXPYTHON="import hax; "
HAXPYTHON+="hax.init(main_data_paths=['/project/lgrandi/pdeperio/161206-hax_debug'], minitree_paths=['.'], pax_version_policy = 'loose'); "
HAXPYTHON+="hax.minitrees.load('Xenon1T_TPC_Kr83m_00000_g4mc_NEST_Patch_pax', ['LargestPeakProperties']);"; python -c "${HAXPYTHON}" # Seems OK
HAXPYTHON+="hax.minitrees.load('Xenon1T_TPC_Kr83m_00183_g4mc_NEST_Patch_pax', ['LargestPeakProperties']);"; python -c "${HAXPYTHON}" # Missing branches
```
producing the two files:
```
Xenon1T_TPC_Kr83m_00000_g4mc_NEST_Patch_pax_LargestPeakProperties.root # Seems OK
Xenon1T_TPC_Kr83m_00183_g4mc_NEST_Patch_pax_LargestPeakProperties.root # Missing branches
```

**Comment by JelleAalbers** [comment]
Is it possible there are no lone hits in some datasets? Since it is simulated data this seems a possibility, and it would most easily explain what you are seeing. LargestPeakProperties doesn't know what all possible peak types are, it just adds columns (which turn into branches when saved to root) for all the peak types it encounters.

**Comment by pdeperio** [comment]
OK, I too thought this might be exactly the case. This is a problem for concatenating (hadd'ing) files and analyses that predefine these branches. Can you think of a solution? How about creating the branches anyway from the list of possible peak types in pax (this is what I did a long time ago with my C++ flattener)?

**Comment by JelleAalbers** [comment]
Sure, I can add that for this treemaker. Is it ok if the numbers for those branches are nans? 

This may be a recurring problem however, as minitrees aren't required to output a stable list of columns. If there is no way of working around this problem on the hadd side, perhaps we should consider this as a requirement/option for at least the standard minitrees.

**Comment by pdeperio** [comment]
Yes, would be great if this is standard behavior for all minitrees. 

Is it possible to just leave them empty for each event? Or is the compression fine with nan?

**Comment by JelleAalbers** [comment]
I think 4ec4beed0a45deb388c18729449646c4a0faa176 should solve this.

**Comment by pdeperio** [comment]
Now also ```alt_s1_interaction_z``` in ```Extended```

**Comment by pdeperio** [comment]
> Patrick de Perio @pdeperio May 30 16:47
>hi jelle. is your check to always create the ROOT branch even though the variable/array is not filled in the first event working for all treemakers?
>
>Jelle Aalbers @JelleAalbers 03:06
>There is no such check, I added this to a specific minitree when you asked (forget which, maybe LargestPeakProperties?), but there's not a general mechanism to do this.

@feigaodm or @JelleAalbers would you be able to make this general?  or implement in all existing treemakers?  ```lax``` will fail otherwise.
