### ISSUE TITLE
Can't find variables CSV file

### ISSUE THREAD

**Issue by tunnell** [XENON1T/hax#66]
Why split the variables up?

OSError: File b'/Users/tunnell/Work/anaconda/envs/xenon_stack/lib/python3.4/site-packages/hax-1.3.0-py3.4.egg/hax/sc_variables.csv' does not exist

I don't think you included this file in the setup.py @JelleAalbers

**Comment by JelleAalbers** [comment]
Sorry about that, https://github.com/XENON1T/hax/commit/4cb3d4c96b33b0fb923344108d37083579d83b9a. I guess this is a disadvantage of developing with setup.py develop...

**Comment by JelleAalbers** [comment]
But https://github.com/XENON1T/hax/blob/master/hax/sc_variables.csv looks pretty
