### ISSUE TITLE
hax.init() gives error

### ISSUE THREAD

**Issue by ErikHogenbirk** [XENON1T/hax#8]
https://gist.github.com/ErikHogenbirk/663a3511a272c12098ce

Just pulled the latest version this afternoon, using examples/07_check_data.ipynb, only first cell.
Relevant code:

  import hax # (works fine)
  hax.init()

**Comment by JelleAalbers** [comment]
Thanks, should be fixed in 2ab2bcd1e48a4445ebb9f5f8155c4e77ebb78525

**Comment by ErikHogenbirk** [comment]
Will check it out, thnx

**Comment by ErikHogenbirk** [comment]
Works all right now, I see you're changing the ways to configure hax. Took me some time to figure that one out exactly ;)
