### ISSUE TITLE
Error in looproot

### ISSUE THREAD

**Issue by ErikHogenbirk** [XENON1T/hax#9]
Here's a brand new bug report :)

https://gist.github.com/ErikHogenbirk/5da9801d81b253ef7717

Seems it asks for hax CONFIG, but is that still in the latest hax version?

**Comment by JelleAalbers** [comment]
Thanks! Hope this fixed it.

**Comment by ErikHogenbirk** [comment]
Sure did :) thanks for the fast fix!
