### ISSUE TITLE
Version requirement mismatch

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/hax#97]
Get this error:
```
KeyError: 'rz_position_distortion_map'
```
using hax v1.4.3 with pax_v6.2.0. I guess since it's not implemented back then.

Can we try to specify version requirements for all our packages (hax, lax, cax) more stringently?

**Comment by JelleAalbers** [comment]
Thanks for reporting, but the dependency here is by mistake: I will remove it.

**Comment by JelleAalbers** [comment]
641d99de2ef64c051989e41213bb392713c32ef4 should fix this, let me know if you see further issues with older pax versions.
